steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/devops4-401021/website-tools/image-wordpress', '.' ]

images :
- 'us-central1-docker.pkg.dev/devops4-401021/website-tools/image-wordpress'